[WIP] Identity management
getupio-undistro/undistro pull request #255
Opened 2021-07-16 00:40 UTC by joivo

- Single entry point to handle authzn

2021-07-16 02:01 UTC, felipeweb requested changes

2021-07-16 02:01 UTC, felipeweb commented on controllers/app/identity_controller.go
> +	conciergeDeploy := appsv1.Deployment{}
use helm release to check if installed link here https://github.com/getupio-undistro/undistro/blob/main/controllers/app/defaultpolicies_controller.go#L139

2021-07-16 13:55 UTC, torr-c approved these changes

2021-07-20 16:29 UTC, torr-c approved these changes

2021-07-20 17:52 UTC, torr-c approved these changes

2021-07-21 13:19 UTC, torr-c approved these changes

2021-07-22 13:23 UTC, torr-c approved these changes

2021-07-26 12:26 UTC, torr-c approved these changes

2021-07-26 23:35 UTC, felipeweb commented
open a new branch this is too old

2021-07-26 23:35 UTC, closed without merging