OpenStack integration
getupio-undistro/undistro pull request #298
Opened 2021-08-26 19:28 UTC by raildo

Adding the infrastructure template and custom resources for configuring
the Cluster API provider for OpenStack, also adding the templates
for the variables needed for setting an environment in a OpenStack
Cloud.

2021-09-06 18:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/getupio-undistro/undistro?pullRequest=298) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/getupio-undistro/undistro?pullRequest=298) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: joivo<br/>:white_check_mark: felipeweb<br/>:x: raildomascena<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/getupio-undistro/undistro?pullRequest=298) it.</sub>

2021-09-14 20:40 UTC, felipeweb requested changes

2021-09-14 20:40 UTC, felipeweb commented on pkg/fs/clustertemplates/openstack/openstack-provider.yaml
> +  name: ${CLUSTER_NAME}
need to use helm chart notation instead of environment variable

2021-09-14 20:40 UTC, felipeweb commented on pkg/fs/clustertemplates/openstack/openstack-provider.yaml
> +      cidrBlocks: ["192.168.0.0/16"] # CIDR block used by Calico.
do not use it hardcoded get info from cluster object

2021-09-14 20:40 UTC, felipeweb commented on charts/undistro-openstack/templates/credentials.yaml
> +  openstack_image_name: {{ .openstack_image | b64enc}}
This information change for each cluster and this secret is global to the OpenStack provider

2021-09-25 21:24 UTC, felipeweb approved these changes

2021-09-27 13:14 UTC, joivo approved these changes

2021-09-27 17:55 UTC, merged