Resources deletion
getupio-undistro/undistro pull request #355
Opened 2021-11-04 12:52 UTC by joivo

2021-11-04 13:16 UTC, torr-c approved these changes

2021-11-11 21:46 UTC, felipeweb requested changes

2021-11-11 21:46 UTC, felipeweb commented on controllers/app/helmrelease_controller.go
> +		}
need to check error if has error return notReady status instead ready

2021-11-12 16:24 UTC, felipeweb approved these changes

2021-11-12 16:25 UTC, merged