Upgrade Supervisor & Concierge charts
getupio-undistro/undistro pull request #398
Opened 2021-12-14 21:36 UTC by joivo

## Description
Please include a summary of the change, the motivation, and any additional context that helps others understand your PR.

## Linked Issues
If these changes close one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/getupio-undistro/.github/labels?q=Type%3A)
- [ ] I have documented my code (if applicable)
- [ ] My changes are covered by tests

2021-12-14 21:42 UTC, felipeweb requested changes

2021-12-14 21:42 UTC, felipeweb commented on charts/pinniped-concierge/values.yaml
> +  repository: nginx
nginx?

2021-12-15 00:58 UTC, joivo commented on charts/pinniped-concierge/values.yaml
> +  repository: nginx
the `values` is not in use yet

2021-12-15 17:23 UTC, felipeweb approved these changes

2021-12-15 18:37 UTC, merged