Cluster deletion never ending
getupio-undistro/undistro pull request #417
Opened 2022-01-03 14:28 UTC by joivo

## Checklist
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/getupio-undistro/.github/labels?q=Type%3A)
- [ ] I have documented my code (if applicable)
- [ ] My changes are covered by tests

2022-01-03 14:51 UTC, carlostrr approved these changes

2022-01-04 17:06 UTC, raildo requested changes
Before we have this PR merged, can you squash those commits and provide a better commit message describing exactly the root cause and what was changed in order to have this bug fixed?

2022-01-05 13:44 UTC, raildo commented on apis/app/v1alpha1/cluster_webhook.go
> +			"field is immutable",
It doesn't need to be made on this PR, but would be nice to have a class or file with all the error messages and we could just reference it on here. That would make easier to update and keep the track of the error messages, and also reuse them in other places.

2022-01-05 13:44 UTC, raildo commented on controllers/app/cluster_controller.go
> +	log.Info("Deleting CAPI Cluster")
This can be done later as well, but would be nice to add some more details on this log messages, such as the cluster name or uid...

2022-01-05 13:44 UTC, raildo commented on controllers/app/cluster_controller.go
> +	log.Info("Cluster is under deletion")
same comment as before

2022-01-05 13:45 UTC, raildo approved these changes

2022-01-05 13:52 UTC, joivo commented on controllers/app/cluster_controller.go
> +	log.Info("Deleting CAPI Cluster")
this type of generic info about the cluster is attached to log [here](https://github.com/getupio-undistro/undistro/blob/cdc8c15de10170f1a0206cf129f211dc5eba621a/controllers/app/cluster_controller.go#L71). however, the uid is not in the keys/values yet. I'II addresses this.

2022-01-05 14:15 UTC, joivo commented on apis/app/v1alpha1/cluster_webhook.go
> +			"field is immutable",
addressed in this pr.

2022-01-05 22:33 UTC, merged